// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trd_FlowSummary.proto

#ifndef PROTOBUF_Trd_5fFlowSummary_2eproto__INCLUDED
#define PROTOBUF_Trd_5fFlowSummary_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "Trd_Common.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_Trd_5fFlowSummary_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsFlowSummaryInfoImpl();
void InitDefaultsFlowSummaryInfo();
void InitDefaultsC2SImpl();
void InitDefaultsC2S();
void InitDefaultsS2CImpl();
void InitDefaultsS2C();
void InitDefaultsRequestImpl();
void InitDefaultsRequest();
void InitDefaultsResponseImpl();
void InitDefaultsResponse();
inline void InitDefaults() {
  InitDefaultsFlowSummaryInfo();
  InitDefaultsC2S();
  InitDefaultsS2C();
  InitDefaultsRequest();
  InitDefaultsResponse();
}
}  // namespace protobuf_Trd_5fFlowSummary_2eproto
namespace Trd_FlowSummary {
class C2S;
class C2SDefaultTypeInternal;
extern C2SDefaultTypeInternal _C2S_default_instance_;
class FlowSummaryInfo;
class FlowSummaryInfoDefaultTypeInternal;
extern FlowSummaryInfoDefaultTypeInternal _FlowSummaryInfo_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class S2C;
class S2CDefaultTypeInternal;
extern S2CDefaultTypeInternal _S2C_default_instance_;
}  // namespace Trd_FlowSummary
namespace Trd_FlowSummary {

enum TrdCashFlowDirection {
  TrdCashFlowDirection_Unknown = 0,
  TrdCashFlowDirection_In = 1,
  TrdCashFlowDirection_Out = 2
};
bool TrdCashFlowDirection_IsValid(int value);
const TrdCashFlowDirection TrdCashFlowDirection_MIN = TrdCashFlowDirection_Unknown;
const TrdCashFlowDirection TrdCashFlowDirection_MAX = TrdCashFlowDirection_Out;
const int TrdCashFlowDirection_ARRAYSIZE = TrdCashFlowDirection_MAX + 1;

const ::google::protobuf::EnumDescriptor* TrdCashFlowDirection_descriptor();
inline const ::std::string& TrdCashFlowDirection_Name(TrdCashFlowDirection value) {
  return ::google::protobuf::internal::NameOfEnum(
    TrdCashFlowDirection_descriptor(), value);
}
inline bool TrdCashFlowDirection_Parse(
    const ::std::string& name, TrdCashFlowDirection* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TrdCashFlowDirection>(
    TrdCashFlowDirection_descriptor(), name, value);
}
// ===================================================================

class FlowSummaryInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_FlowSummary.FlowSummaryInfo) */ {
 public:
  FlowSummaryInfo();
  virtual ~FlowSummaryInfo();

  FlowSummaryInfo(const FlowSummaryInfo& from);

  inline FlowSummaryInfo& operator=(const FlowSummaryInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FlowSummaryInfo(FlowSummaryInfo&& from) noexcept
    : FlowSummaryInfo() {
    *this = ::std::move(from);
  }

  inline FlowSummaryInfo& operator=(FlowSummaryInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FlowSummaryInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FlowSummaryInfo* internal_default_instance() {
    return reinterpret_cast<const FlowSummaryInfo*>(
               &_FlowSummaryInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(FlowSummaryInfo* other);
  friend void swap(FlowSummaryInfo& a, FlowSummaryInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FlowSummaryInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  FlowSummaryInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FlowSummaryInfo& from);
  void MergeFrom(const FlowSummaryInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FlowSummaryInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string clearingDate = 1;
  bool has_clearingdate() const;
  void clear_clearingdate();
  static const int kClearingDateFieldNumber = 1;
  const ::std::string& clearingdate() const;
  void set_clearingdate(const ::std::string& value);
  #if LANG_CXX11
  void set_clearingdate(::std::string&& value);
  #endif
  void set_clearingdate(const char* value);
  void set_clearingdate(const char* value, size_t size);
  ::std::string* mutable_clearingdate();
  ::std::string* release_clearingdate();
  void set_allocated_clearingdate(::std::string* clearingdate);

  // optional string settlementDate = 2;
  bool has_settlementdate() const;
  void clear_settlementdate();
  static const int kSettlementDateFieldNumber = 2;
  const ::std::string& settlementdate() const;
  void set_settlementdate(const ::std::string& value);
  #if LANG_CXX11
  void set_settlementdate(::std::string&& value);
  #endif
  void set_settlementdate(const char* value);
  void set_settlementdate(const char* value, size_t size);
  ::std::string* mutable_settlementdate();
  ::std::string* release_settlementdate();
  void set_allocated_settlementdate(::std::string* settlementdate);

  // optional string cashFlowType = 4;
  bool has_cashflowtype() const;
  void clear_cashflowtype();
  static const int kCashFlowTypeFieldNumber = 4;
  const ::std::string& cashflowtype() const;
  void set_cashflowtype(const ::std::string& value);
  #if LANG_CXX11
  void set_cashflowtype(::std::string&& value);
  #endif
  void set_cashflowtype(const char* value);
  void set_cashflowtype(const char* value, size_t size);
  ::std::string* mutable_cashflowtype();
  ::std::string* release_cashflowtype();
  void set_allocated_cashflowtype(::std::string* cashflowtype);

  // optional string cashFlowRemark = 7;
  bool has_cashflowremark() const;
  void clear_cashflowremark();
  static const int kCashFlowRemarkFieldNumber = 7;
  const ::std::string& cashflowremark() const;
  void set_cashflowremark(const ::std::string& value);
  #if LANG_CXX11
  void set_cashflowremark(::std::string&& value);
  #endif
  void set_cashflowremark(const char* value);
  void set_cashflowremark(const char* value, size_t size);
  ::std::string* mutable_cashflowremark();
  ::std::string* release_cashflowremark();
  void set_allocated_cashflowremark(::std::string* cashflowremark);

  // optional int32 currency = 3;
  bool has_currency() const;
  void clear_currency();
  static const int kCurrencyFieldNumber = 3;
  ::google::protobuf::int32 currency() const;
  void set_currency(::google::protobuf::int32 value);

  // optional int32 cashFlowDirection = 5;
  bool has_cashflowdirection() const;
  void clear_cashflowdirection();
  static const int kCashFlowDirectionFieldNumber = 5;
  ::google::protobuf::int32 cashflowdirection() const;
  void set_cashflowdirection(::google::protobuf::int32 value);

  // optional double cashFlowAmount = 6;
  bool has_cashflowamount() const;
  void clear_cashflowamount();
  static const int kCashFlowAmountFieldNumber = 6;
  double cashflowamount() const;
  void set_cashflowamount(double value);

  // optional uint64 cashFlowID = 8;
  bool has_cashflowid() const;
  void clear_cashflowid();
  static const int kCashFlowIDFieldNumber = 8;
  ::google::protobuf::uint64 cashflowid() const;
  void set_cashflowid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Trd_FlowSummary.FlowSummaryInfo)
 private:
  void set_has_clearingdate();
  void clear_has_clearingdate();
  void set_has_settlementdate();
  void clear_has_settlementdate();
  void set_has_currency();
  void clear_has_currency();
  void set_has_cashflowtype();
  void clear_has_cashflowtype();
  void set_has_cashflowdirection();
  void clear_has_cashflowdirection();
  void set_has_cashflowamount();
  void clear_has_cashflowamount();
  void set_has_cashflowremark();
  void clear_has_cashflowremark();
  void set_has_cashflowid();
  void clear_has_cashflowid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr clearingdate_;
  ::google::protobuf::internal::ArenaStringPtr settlementdate_;
  ::google::protobuf::internal::ArenaStringPtr cashflowtype_;
  ::google::protobuf::internal::ArenaStringPtr cashflowremark_;
  ::google::protobuf::int32 currency_;
  ::google::protobuf::int32 cashflowdirection_;
  double cashflowamount_;
  ::google::protobuf::uint64 cashflowid_;
  friend struct ::protobuf_Trd_5fFlowSummary_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fFlowSummary_2eproto::InitDefaultsFlowSummaryInfoImpl();
};
// -------------------------------------------------------------------

class C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_FlowSummary.C2S) */ {
 public:
  C2S();
  virtual ~C2S();

  C2S(const C2S& from);

  inline C2S& operator=(const C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  C2S(C2S&& from) noexcept
    : C2S() {
    *this = ::std::move(from);
  }

  inline C2S& operator=(C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const C2S* internal_default_instance() {
    return reinterpret_cast<const C2S*>(
               &_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(C2S* other);
  friend void swap(C2S& a, C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S& from);
  void MergeFrom(const C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string clearingDate = 2;
  bool has_clearingdate() const;
  void clear_clearingdate();
  static const int kClearingDateFieldNumber = 2;
  const ::std::string& clearingdate() const;
  void set_clearingdate(const ::std::string& value);
  #if LANG_CXX11
  void set_clearingdate(::std::string&& value);
  #endif
  void set_clearingdate(const char* value);
  void set_clearingdate(const char* value, size_t size);
  ::std::string* mutable_clearingdate();
  ::std::string* release_clearingdate();
  void set_allocated_clearingdate(::std::string* clearingdate);

  // required .Trd_Common.TrdHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::Trd_Common::TrdHeader& header() const;
  ::Trd_Common::TrdHeader* release_header();
  ::Trd_Common::TrdHeader* mutable_header();
  void set_allocated_header(::Trd_Common::TrdHeader* header);

  // optional int32 cashFlowDirection = 3;
  bool has_cashflowdirection() const;
  void clear_cashflowdirection();
  static const int kCashFlowDirectionFieldNumber = 3;
  ::google::protobuf::int32 cashflowdirection() const;
  void set_cashflowdirection(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Trd_FlowSummary.C2S)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_clearingdate();
  void clear_has_clearingdate();
  void set_has_cashflowdirection();
  void clear_has_cashflowdirection();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr clearingdate_;
  ::Trd_Common::TrdHeader* header_;
  ::google::protobuf::int32 cashflowdirection_;
  friend struct ::protobuf_Trd_5fFlowSummary_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fFlowSummary_2eproto::InitDefaultsC2SImpl();
};
// -------------------------------------------------------------------

class S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_FlowSummary.S2C) */ {
 public:
  S2C();
  virtual ~S2C();

  S2C(const S2C& from);

  inline S2C& operator=(const S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  S2C(S2C&& from) noexcept
    : S2C() {
    *this = ::std::move(from);
  }

  inline S2C& operator=(S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const S2C* internal_default_instance() {
    return reinterpret_cast<const S2C*>(
               &_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(S2C* other);
  friend void swap(S2C& a, S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C& from);
  void MergeFrom(const S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Trd_FlowSummary.FlowSummaryInfo flowSummaryInfoList = 2;
  int flowsummaryinfolist_size() const;
  void clear_flowsummaryinfolist();
  static const int kFlowSummaryInfoListFieldNumber = 2;
  const ::Trd_FlowSummary::FlowSummaryInfo& flowsummaryinfolist(int index) const;
  ::Trd_FlowSummary::FlowSummaryInfo* mutable_flowsummaryinfolist(int index);
  ::Trd_FlowSummary::FlowSummaryInfo* add_flowsummaryinfolist();
  ::google::protobuf::RepeatedPtrField< ::Trd_FlowSummary::FlowSummaryInfo >*
      mutable_flowsummaryinfolist();
  const ::google::protobuf::RepeatedPtrField< ::Trd_FlowSummary::FlowSummaryInfo >&
      flowsummaryinfolist() const;

  // required .Trd_Common.TrdHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::Trd_Common::TrdHeader& header() const;
  ::Trd_Common::TrdHeader* release_header();
  ::Trd_Common::TrdHeader* mutable_header();
  void set_allocated_header(::Trd_Common::TrdHeader* header);

  // @@protoc_insertion_point(class_scope:Trd_FlowSummary.S2C)
 private:
  void set_has_header();
  void clear_has_header();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Trd_FlowSummary::FlowSummaryInfo > flowsummaryinfolist_;
  ::Trd_Common::TrdHeader* header_;
  friend struct ::protobuf_Trd_5fFlowSummary_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fFlowSummary_2eproto::InitDefaultsS2CImpl();
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_FlowSummary.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const PROTOBUF_FINAL { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Trd_FlowSummary.C2S c2s = 1;
  bool has_c2s() const;
  void clear_c2s();
  static const int kC2SFieldNumber = 1;
  const ::Trd_FlowSummary::C2S& c2s() const;
  ::Trd_FlowSummary::C2S* release_c2s();
  ::Trd_FlowSummary::C2S* mutable_c2s();
  void set_allocated_c2s(::Trd_FlowSummary::C2S* c2s);

  // @@protoc_insertion_point(class_scope:Trd_FlowSummary.Request)
 private:
  void set_has_c2s();
  void clear_has_c2s();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Trd_FlowSummary::C2S* c2s_;
  friend struct ::protobuf_Trd_5fFlowSummary_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fFlowSummary_2eproto::InitDefaultsRequestImpl();
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Trd_FlowSummary.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const PROTOBUF_FINAL { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string retMsg = 2;
  bool has_retmsg() const;
  void clear_retmsg();
  static const int kRetMsgFieldNumber = 2;
  const ::std::string& retmsg() const;
  void set_retmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_retmsg(::std::string&& value);
  #endif
  void set_retmsg(const char* value);
  void set_retmsg(const char* value, size_t size);
  ::std::string* mutable_retmsg();
  ::std::string* release_retmsg();
  void set_allocated_retmsg(::std::string* retmsg);

  // optional .Trd_FlowSummary.S2C s2c = 4;
  bool has_s2c() const;
  void clear_s2c();
  static const int kS2CFieldNumber = 4;
  const ::Trd_FlowSummary::S2C& s2c() const;
  ::Trd_FlowSummary::S2C* release_s2c();
  ::Trd_FlowSummary::S2C* mutable_s2c();
  void set_allocated_s2c(::Trd_FlowSummary::S2C* s2c);

  // optional int32 errCode = 3;
  bool has_errcode() const;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 3;
  ::google::protobuf::int32 errcode() const;
  void set_errcode(::google::protobuf::int32 value);

  // required int32 retType = 1 [default = -400];
  bool has_rettype() const;
  void clear_rettype();
  static const int kRetTypeFieldNumber = 1;
  ::google::protobuf::int32 rettype() const;
  void set_rettype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Trd_FlowSummary.Response)
 private:
  void set_has_rettype();
  void clear_has_rettype();
  void set_has_retmsg();
  void clear_has_retmsg();
  void set_has_errcode();
  void clear_has_errcode();
  void set_has_s2c();
  void clear_has_s2c();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr retmsg_;
  ::Trd_FlowSummary::S2C* s2c_;
  ::google::protobuf::int32 errcode_;
  ::google::protobuf::int32 rettype_;
  friend struct ::protobuf_Trd_5fFlowSummary_2eproto::TableStruct;
  friend void ::protobuf_Trd_5fFlowSummary_2eproto::InitDefaultsResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FlowSummaryInfo

// optional string clearingDate = 1;
inline bool FlowSummaryInfo::has_clearingdate() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FlowSummaryInfo::set_has_clearingdate() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FlowSummaryInfo::clear_has_clearingdate() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FlowSummaryInfo::clear_clearingdate() {
  clearingdate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_clearingdate();
}
inline const ::std::string& FlowSummaryInfo::clearingdate() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
  return clearingdate_.GetNoArena();
}
inline void FlowSummaryInfo::set_clearingdate(const ::std::string& value) {
  set_has_clearingdate();
  clearingdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
}
#if LANG_CXX11
inline void FlowSummaryInfo::set_clearingdate(::std::string&& value) {
  set_has_clearingdate();
  clearingdate_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
}
#endif
inline void FlowSummaryInfo::set_clearingdate(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_clearingdate();
  clearingdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
}
inline void FlowSummaryInfo::set_clearingdate(const char* value, size_t size) {
  set_has_clearingdate();
  clearingdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
}
inline ::std::string* FlowSummaryInfo::mutable_clearingdate() {
  set_has_clearingdate();
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
  return clearingdate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FlowSummaryInfo::release_clearingdate() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
  clear_has_clearingdate();
  return clearingdate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FlowSummaryInfo::set_allocated_clearingdate(::std::string* clearingdate) {
  if (clearingdate != NULL) {
    set_has_clearingdate();
  } else {
    clear_has_clearingdate();
  }
  clearingdate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clearingdate);
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.FlowSummaryInfo.clearingDate)
}

// optional string settlementDate = 2;
inline bool FlowSummaryInfo::has_settlementdate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FlowSummaryInfo::set_has_settlementdate() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FlowSummaryInfo::clear_has_settlementdate() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FlowSummaryInfo::clear_settlementdate() {
  settlementdate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_settlementdate();
}
inline const ::std::string& FlowSummaryInfo::settlementdate() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
  return settlementdate_.GetNoArena();
}
inline void FlowSummaryInfo::set_settlementdate(const ::std::string& value) {
  set_has_settlementdate();
  settlementdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
}
#if LANG_CXX11
inline void FlowSummaryInfo::set_settlementdate(::std::string&& value) {
  set_has_settlementdate();
  settlementdate_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
}
#endif
inline void FlowSummaryInfo::set_settlementdate(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_settlementdate();
  settlementdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
}
inline void FlowSummaryInfo::set_settlementdate(const char* value, size_t size) {
  set_has_settlementdate();
  settlementdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
}
inline ::std::string* FlowSummaryInfo::mutable_settlementdate() {
  set_has_settlementdate();
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
  return settlementdate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FlowSummaryInfo::release_settlementdate() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
  clear_has_settlementdate();
  return settlementdate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FlowSummaryInfo::set_allocated_settlementdate(::std::string* settlementdate) {
  if (settlementdate != NULL) {
    set_has_settlementdate();
  } else {
    clear_has_settlementdate();
  }
  settlementdate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), settlementdate);
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.FlowSummaryInfo.settlementDate)
}

// optional int32 currency = 3;
inline bool FlowSummaryInfo::has_currency() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void FlowSummaryInfo::set_has_currency() {
  _has_bits_[0] |= 0x00000010u;
}
inline void FlowSummaryInfo::clear_has_currency() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void FlowSummaryInfo::clear_currency() {
  currency_ = 0;
  clear_has_currency();
}
inline ::google::protobuf::int32 FlowSummaryInfo::currency() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.currency)
  return currency_;
}
inline void FlowSummaryInfo::set_currency(::google::protobuf::int32 value) {
  set_has_currency();
  currency_ = value;
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.currency)
}

// optional string cashFlowType = 4;
inline bool FlowSummaryInfo::has_cashflowtype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FlowSummaryInfo::set_has_cashflowtype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FlowSummaryInfo::clear_has_cashflowtype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FlowSummaryInfo::clear_cashflowtype() {
  cashflowtype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cashflowtype();
}
inline const ::std::string& FlowSummaryInfo::cashflowtype() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
  return cashflowtype_.GetNoArena();
}
inline void FlowSummaryInfo::set_cashflowtype(const ::std::string& value) {
  set_has_cashflowtype();
  cashflowtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
}
#if LANG_CXX11
inline void FlowSummaryInfo::set_cashflowtype(::std::string&& value) {
  set_has_cashflowtype();
  cashflowtype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
}
#endif
inline void FlowSummaryInfo::set_cashflowtype(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cashflowtype();
  cashflowtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
}
inline void FlowSummaryInfo::set_cashflowtype(const char* value, size_t size) {
  set_has_cashflowtype();
  cashflowtype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
}
inline ::std::string* FlowSummaryInfo::mutable_cashflowtype() {
  set_has_cashflowtype();
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
  return cashflowtype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FlowSummaryInfo::release_cashflowtype() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
  clear_has_cashflowtype();
  return cashflowtype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FlowSummaryInfo::set_allocated_cashflowtype(::std::string* cashflowtype) {
  if (cashflowtype != NULL) {
    set_has_cashflowtype();
  } else {
    clear_has_cashflowtype();
  }
  cashflowtype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cashflowtype);
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.FlowSummaryInfo.cashFlowType)
}

// optional int32 cashFlowDirection = 5;
inline bool FlowSummaryInfo::has_cashflowdirection() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void FlowSummaryInfo::set_has_cashflowdirection() {
  _has_bits_[0] |= 0x00000020u;
}
inline void FlowSummaryInfo::clear_has_cashflowdirection() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void FlowSummaryInfo::clear_cashflowdirection() {
  cashflowdirection_ = 0;
  clear_has_cashflowdirection();
}
inline ::google::protobuf::int32 FlowSummaryInfo::cashflowdirection() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.cashFlowDirection)
  return cashflowdirection_;
}
inline void FlowSummaryInfo::set_cashflowdirection(::google::protobuf::int32 value) {
  set_has_cashflowdirection();
  cashflowdirection_ = value;
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.cashFlowDirection)
}

// optional double cashFlowAmount = 6;
inline bool FlowSummaryInfo::has_cashflowamount() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void FlowSummaryInfo::set_has_cashflowamount() {
  _has_bits_[0] |= 0x00000040u;
}
inline void FlowSummaryInfo::clear_has_cashflowamount() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void FlowSummaryInfo::clear_cashflowamount() {
  cashflowamount_ = 0;
  clear_has_cashflowamount();
}
inline double FlowSummaryInfo::cashflowamount() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.cashFlowAmount)
  return cashflowamount_;
}
inline void FlowSummaryInfo::set_cashflowamount(double value) {
  set_has_cashflowamount();
  cashflowamount_ = value;
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.cashFlowAmount)
}

// optional string cashFlowRemark = 7;
inline bool FlowSummaryInfo::has_cashflowremark() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void FlowSummaryInfo::set_has_cashflowremark() {
  _has_bits_[0] |= 0x00000008u;
}
inline void FlowSummaryInfo::clear_has_cashflowremark() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void FlowSummaryInfo::clear_cashflowremark() {
  cashflowremark_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cashflowremark();
}
inline const ::std::string& FlowSummaryInfo::cashflowremark() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
  return cashflowremark_.GetNoArena();
}
inline void FlowSummaryInfo::set_cashflowremark(const ::std::string& value) {
  set_has_cashflowremark();
  cashflowremark_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
}
#if LANG_CXX11
inline void FlowSummaryInfo::set_cashflowremark(::std::string&& value) {
  set_has_cashflowremark();
  cashflowremark_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
}
#endif
inline void FlowSummaryInfo::set_cashflowremark(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cashflowremark();
  cashflowremark_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
}
inline void FlowSummaryInfo::set_cashflowremark(const char* value, size_t size) {
  set_has_cashflowremark();
  cashflowremark_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
}
inline ::std::string* FlowSummaryInfo::mutable_cashflowremark() {
  set_has_cashflowremark();
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
  return cashflowremark_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FlowSummaryInfo::release_cashflowremark() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
  clear_has_cashflowremark();
  return cashflowremark_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FlowSummaryInfo::set_allocated_cashflowremark(::std::string* cashflowremark) {
  if (cashflowremark != NULL) {
    set_has_cashflowremark();
  } else {
    clear_has_cashflowremark();
  }
  cashflowremark_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cashflowremark);
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.FlowSummaryInfo.cashFlowRemark)
}

// optional uint64 cashFlowID = 8;
inline bool FlowSummaryInfo::has_cashflowid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void FlowSummaryInfo::set_has_cashflowid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void FlowSummaryInfo::clear_has_cashflowid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void FlowSummaryInfo::clear_cashflowid() {
  cashflowid_ = GOOGLE_ULONGLONG(0);
  clear_has_cashflowid();
}
inline ::google::protobuf::uint64 FlowSummaryInfo::cashflowid() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.FlowSummaryInfo.cashFlowID)
  return cashflowid_;
}
inline void FlowSummaryInfo::set_cashflowid(::google::protobuf::uint64 value) {
  set_has_cashflowid();
  cashflowid_ = value;
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.FlowSummaryInfo.cashFlowID)
}

// -------------------------------------------------------------------

// C2S

// required .Trd_Common.TrdHeader header = 1;
inline bool C2S::has_header() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2S::set_has_header() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2S::clear_has_header() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::Trd_Common::TrdHeader& C2S::header() const {
  const ::Trd_Common::TrdHeader* p = header_;
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.C2S.header)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_Common::TrdHeader*>(
      &::Trd_Common::_TrdHeader_default_instance_);
}
inline ::Trd_Common::TrdHeader* C2S::release_header() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.C2S.header)
  clear_has_header();
  ::Trd_Common::TrdHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::Trd_Common::TrdHeader* C2S::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::Trd_Common::TrdHeader;
  }
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.C2S.header)
  return header_;
}
inline void C2S::set_allocated_header(::Trd_Common::TrdHeader* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.C2S.header)
}

// required string clearingDate = 2;
inline bool C2S::has_clearingdate() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2S::set_has_clearingdate() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2S::clear_has_clearingdate() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2S::clear_clearingdate() {
  clearingdate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_clearingdate();
}
inline const ::std::string& C2S::clearingdate() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.C2S.clearingDate)
  return clearingdate_.GetNoArena();
}
inline void C2S::set_clearingdate(const ::std::string& value) {
  set_has_clearingdate();
  clearingdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.C2S.clearingDate)
}
#if LANG_CXX11
inline void C2S::set_clearingdate(::std::string&& value) {
  set_has_clearingdate();
  clearingdate_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Trd_FlowSummary.C2S.clearingDate)
}
#endif
inline void C2S::set_clearingdate(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_clearingdate();
  clearingdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Trd_FlowSummary.C2S.clearingDate)
}
inline void C2S::set_clearingdate(const char* value, size_t size) {
  set_has_clearingdate();
  clearingdate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Trd_FlowSummary.C2S.clearingDate)
}
inline ::std::string* C2S::mutable_clearingdate() {
  set_has_clearingdate();
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.C2S.clearingDate)
  return clearingdate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* C2S::release_clearingdate() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.C2S.clearingDate)
  clear_has_clearingdate();
  return clearingdate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2S::set_allocated_clearingdate(::std::string* clearingdate) {
  if (clearingdate != NULL) {
    set_has_clearingdate();
  } else {
    clear_has_clearingdate();
  }
  clearingdate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clearingdate);
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.C2S.clearingDate)
}

// optional int32 cashFlowDirection = 3;
inline bool C2S::has_cashflowdirection() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void C2S::set_has_cashflowdirection() {
  _has_bits_[0] |= 0x00000004u;
}
inline void C2S::clear_has_cashflowdirection() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void C2S::clear_cashflowdirection() {
  cashflowdirection_ = 0;
  clear_has_cashflowdirection();
}
inline ::google::protobuf::int32 C2S::cashflowdirection() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.C2S.cashFlowDirection)
  return cashflowdirection_;
}
inline void C2S::set_cashflowdirection(::google::protobuf::int32 value) {
  set_has_cashflowdirection();
  cashflowdirection_ = value;
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.C2S.cashFlowDirection)
}

// -------------------------------------------------------------------

// S2C

// required .Trd_Common.TrdHeader header = 1;
inline bool S2C::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2C::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2C::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Trd_Common::TrdHeader& S2C::header() const {
  const ::Trd_Common::TrdHeader* p = header_;
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.S2C.header)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_Common::TrdHeader*>(
      &::Trd_Common::_TrdHeader_default_instance_);
}
inline ::Trd_Common::TrdHeader* S2C::release_header() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.S2C.header)
  clear_has_header();
  ::Trd_Common::TrdHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::Trd_Common::TrdHeader* S2C::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::Trd_Common::TrdHeader;
  }
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.S2C.header)
  return header_;
}
inline void S2C::set_allocated_header(::Trd_Common::TrdHeader* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.S2C.header)
}

// repeated .Trd_FlowSummary.FlowSummaryInfo flowSummaryInfoList = 2;
inline int S2C::flowsummaryinfolist_size() const {
  return flowsummaryinfolist_.size();
}
inline void S2C::clear_flowsummaryinfolist() {
  flowsummaryinfolist_.Clear();
}
inline const ::Trd_FlowSummary::FlowSummaryInfo& S2C::flowsummaryinfolist(int index) const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.S2C.flowSummaryInfoList)
  return flowsummaryinfolist_.Get(index);
}
inline ::Trd_FlowSummary::FlowSummaryInfo* S2C::mutable_flowsummaryinfolist(int index) {
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.S2C.flowSummaryInfoList)
  return flowsummaryinfolist_.Mutable(index);
}
inline ::Trd_FlowSummary::FlowSummaryInfo* S2C::add_flowsummaryinfolist() {
  // @@protoc_insertion_point(field_add:Trd_FlowSummary.S2C.flowSummaryInfoList)
  return flowsummaryinfolist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Trd_FlowSummary::FlowSummaryInfo >*
S2C::mutable_flowsummaryinfolist() {
  // @@protoc_insertion_point(field_mutable_list:Trd_FlowSummary.S2C.flowSummaryInfoList)
  return &flowsummaryinfolist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Trd_FlowSummary::FlowSummaryInfo >&
S2C::flowsummaryinfolist() const {
  // @@protoc_insertion_point(field_list:Trd_FlowSummary.S2C.flowSummaryInfoList)
  return flowsummaryinfolist_;
}

// -------------------------------------------------------------------

// Request

// required .Trd_FlowSummary.C2S c2s = 1;
inline bool Request::has_c2s() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_c2s() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_c2s() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_c2s() {
  if (c2s_ != NULL) c2s_->Clear();
  clear_has_c2s();
}
inline const ::Trd_FlowSummary::C2S& Request::c2s() const {
  const ::Trd_FlowSummary::C2S* p = c2s_;
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.Request.c2s)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_FlowSummary::C2S*>(
      &::Trd_FlowSummary::_C2S_default_instance_);
}
inline ::Trd_FlowSummary::C2S* Request::release_c2s() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.Request.c2s)
  clear_has_c2s();
  ::Trd_FlowSummary::C2S* temp = c2s_;
  c2s_ = NULL;
  return temp;
}
inline ::Trd_FlowSummary::C2S* Request::mutable_c2s() {
  set_has_c2s();
  if (c2s_ == NULL) {
    c2s_ = new ::Trd_FlowSummary::C2S;
  }
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.Request.c2s)
  return c2s_;
}
inline void Request::set_allocated_c2s(::Trd_FlowSummary::C2S* c2s) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete c2s_;
  }
  if (c2s) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      c2s = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, c2s, submessage_arena);
    }
    set_has_c2s();
  } else {
    clear_has_c2s();
  }
  c2s_ = c2s;
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.Request.c2s)
}

// -------------------------------------------------------------------

// Response

// required int32 retType = 1 [default = -400];
inline bool Response::has_rettype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_rettype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_rettype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_rettype() {
  rettype_ = -400;
  clear_has_rettype();
}
inline ::google::protobuf::int32 Response::rettype() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.Response.retType)
  return rettype_;
}
inline void Response::set_rettype(::google::protobuf::int32 value) {
  set_has_rettype();
  rettype_ = value;
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.Response.retType)
}

// optional string retMsg = 2;
inline bool Response::has_retmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_retmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_retmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_retmsg() {
  retmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_retmsg();
}
inline const ::std::string& Response::retmsg() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.Response.retMsg)
  return retmsg_.GetNoArena();
}
inline void Response::set_retmsg(const ::std::string& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.Response.retMsg)
}
#if LANG_CXX11
inline void Response::set_retmsg(::std::string&& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Trd_FlowSummary.Response.retMsg)
}
#endif
inline void Response::set_retmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Trd_FlowSummary.Response.retMsg)
}
inline void Response::set_retmsg(const char* value, size_t size) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Trd_FlowSummary.Response.retMsg)
}
inline ::std::string* Response::mutable_retmsg() {
  set_has_retmsg();
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.Response.retMsg)
  return retmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_retmsg() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.Response.retMsg)
  clear_has_retmsg();
  return retmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_retmsg(::std::string* retmsg) {
  if (retmsg != NULL) {
    set_has_retmsg();
  } else {
    clear_has_retmsg();
  }
  retmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), retmsg);
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.Response.retMsg)
}

// optional int32 errCode = 3;
inline bool Response::has_errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_errcode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_errcode() {
  errcode_ = 0;
  clear_has_errcode();
}
inline ::google::protobuf::int32 Response::errcode() const {
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.Response.errCode)
  return errcode_;
}
inline void Response::set_errcode(::google::protobuf::int32 value) {
  set_has_errcode();
  errcode_ = value;
  // @@protoc_insertion_point(field_set:Trd_FlowSummary.Response.errCode)
}

// optional .Trd_FlowSummary.S2C s2c = 4;
inline bool Response::has_s2c() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_s2c() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_s2c() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_s2c() {
  if (s2c_ != NULL) s2c_->Clear();
  clear_has_s2c();
}
inline const ::Trd_FlowSummary::S2C& Response::s2c() const {
  const ::Trd_FlowSummary::S2C* p = s2c_;
  // @@protoc_insertion_point(field_get:Trd_FlowSummary.Response.s2c)
  return p != NULL ? *p : *reinterpret_cast<const ::Trd_FlowSummary::S2C*>(
      &::Trd_FlowSummary::_S2C_default_instance_);
}
inline ::Trd_FlowSummary::S2C* Response::release_s2c() {
  // @@protoc_insertion_point(field_release:Trd_FlowSummary.Response.s2c)
  clear_has_s2c();
  ::Trd_FlowSummary::S2C* temp = s2c_;
  s2c_ = NULL;
  return temp;
}
inline ::Trd_FlowSummary::S2C* Response::mutable_s2c() {
  set_has_s2c();
  if (s2c_ == NULL) {
    s2c_ = new ::Trd_FlowSummary::S2C;
  }
  // @@protoc_insertion_point(field_mutable:Trd_FlowSummary.Response.s2c)
  return s2c_;
}
inline void Response::set_allocated_s2c(::Trd_FlowSummary::S2C* s2c) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete s2c_;
  }
  if (s2c) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      s2c = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, s2c, submessage_arena);
    }
    set_has_s2c();
  } else {
    clear_has_s2c();
  }
  s2c_ = s2c;
  // @@protoc_insertion_point(field_set_allocated:Trd_FlowSummary.Response.s2c)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Trd_FlowSummary

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Trd_FlowSummary::TrdCashFlowDirection> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Trd_FlowSummary::TrdCashFlowDirection>() {
  return ::Trd_FlowSummary::TrdCashFlowDirection_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Trd_5fFlowSummary_2eproto__INCLUDED
